name: Daily Cypress Tests

on:
  schedule:
    # This cron expression schedules the job to run every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [1.2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Cypress Test Suite
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
          env: grepTags=@smoke
        env:
          CYPRESS_RECORD_KEY: '2cbc1c99-1a42-4065-900d-f116c656d183'
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
